code/COVID-AID/chat/urls.py
"""为chat应用定义路由"""

from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('get_chat_room/<to_username>/', views.GetChatRoomView.as_view(), name='get_chat_room'),
    path('new_group_chat/', views.NewGroupChatView.as_view(), name='new_group_chat'),
    path('create_group_chat/', views.CreateGroupChatView.as_view(), name='create_group_chat'),
    path('get_group_chat/<room_name>/', views.GetGroupChatView.as_view(), name='get_group_chat'),
    path('chat_room/<room_name>/', views.room, name='chat_room'),
    path('index/', views.IndexView.as_view(), name='chat_index'),
]

code/COVID-AID/diagnosis/urls.py
"""为diagnosis应用定义路由"""

from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'diagnosis'
urlpatterns = [
    path('pic_upload/', views.PicUploadView.as_view(), name='pic_upload'),
    path('pic_process/', views.PicProcessView.as_view(), name='pic_process'),
    path('result/', views.ResultView.as_view(), name='result'),
    path('main_layout/', views.MainLayoutView.as_view(), name='main_layout'),
    path('result_list/', views.ResultListView.as_view(), name='result_list'),
    path('result_detail/<num>/', views.ResultDetailView.as_view(), name='detail'),
    path('append_result/<img_url>/', views.PicProcessView.getPicture),
    path('update_result/<checked>/<result>/<idx>/', views.UpdateResultView.as_view())
]

code/COVID-AID/epidemic_map/urls.py
"""为epidemic_map应用定义路由"""

from django.urls import path
from . import views

app_name = 'epidemic_map'
urlpatterns = [
    path('', views.EpidemicMapView.as_view(), name='epidemic-map'),
    path('location_upload/', views.LocatinoUploadView.as_view(), name='location-upload'),
]

code/COVID-AID/login/urls.py
from django.urls import path, re_path
from .views import quit, verify_account  # , page_error, page_not_found_error
from . import views

app_name = 'login'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),  # 登录系统
    path('quit/', quit, name='quit'),  # 退出系统
    path('verify_account/', verify_account, name='verify_account'),  # 异步验证账号密码
    re_path(r'usernames/(?P<username>[a-zA-Z0-9_\u4e00-\u9fa5\s·]+)/count/$', views.UsernameCountView.as_view()),
    re_path(
        r'phones/(?P<phone>[1](([3][0-9])|([4][5-9])|([5][0-3,5-9])|([6][5,6])|([7][0-8])|([8][0-9])|([9][1,8,9]))[0-9]{8})/count/$',
        views.PhoneCountView.as_view()),
    path('', views.IndexView.as_view(), name='index'),
]
# handler404 = page_not_found_error
# handler500 = page_error

code/COVID-AID/statistic/urls.py
from django.urls import path
from . import views
app_name = 'statistic'
urlpatterns = [
    path('covid-19/ctmap', views.CtView.as_view(),name = 'covid_19_ctmap'),
    path('covid-19/csmap', views.CsView.as_view(),name = 'covid_19_csmap'),
    path('covid-19/fimap', views.CdView.as_view(),name = 'covid_19_fimap'),
    path('covid-19/gtmap', views.GtView.as_view(),name = 'covid_19_gtmap'),
    path('covid-19/gsmap', views.GsView.as_view(),name = 'covid_19_gsmap'),
    path('covid-19/ftemap', views.GdView.as_view(),name = 'covid_19_ftemap'),
    path('covid-19',views.IndexView.as_view(),name = 'covid_19'),
    path('covid-19/update',views.update,name = 'covid_19_update'),
]

code/COVID-AID/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="zh">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Covid-aid</title>
    <link rel="apple-touch-icon" sizes="180x180" href="favicon.ico">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon.ico">
    <!-- layui样式 -->
    <link rel="stylesheet" href="{% static 'Y-Admin/layui/css/layui.css' %}">
    <!-- Y-Admin核心样式 -->
    <link rel="stylesheet" href="{% static 'Y-Admin/css/yadmin.css' %}">
    <!-- 公共样式 -->
    <link rel="stylesheet" href="{% static 'Y-Admin/css/common.css' %}">
    <!-- 图标 -->
    <link rel="stylesheet" href="{% static 'Y-Admin/static/remixicon/fonts/remixicon.css' %}">
    <!-- 首页样式（只为此页面使用） -->
    <link rel="stylesheet" href="{% static 'Y-Admin/css/index.css' %}">
</head>

<body class="layui-layout-body">

<div class="layui-layout layui-layout-admin">

    <div class="layui-header">
        <!-- logo 区域 -->
        <div class="layui-logo">
            <!--                <img src="images/security.png" alt="logo" style="margin-left: -5px;" />-->
            <cite>
                Covid-aid
            </cite>
        </div>

        <!-- 头部区域 -->
        <ul class="layui-nav layui-layout-left">
            <li class="layui-nav-item" lay-unselect>
                <a lay-event="flexible" title="侧边伸缩">
                    <i class="layui-icon layui-icon-shrink-right"></i>
                </a>
            </li>
            <!-- 面包屑 -->
            <span class="layui-breadcrumb layui-anim layui-anim-up">
                    <a><cite>首页</cite></a>
            </span>
        </ul>

        <!-- 头像区域 -->
        <ul class="layui-nav layui-layout-right">

            <li class="layui-nav-item feature-items">
                <a id="screenFull" lay-event="screenFull" title="全屏">
                    <i class="ri-fullscreen-line"></i>
                </a>
                <a id="screenRestore" lay-event="screenRestore" title="退出全屏" style="display: none;">
                    <i class="ri-fullscreen-exit-line"></i>
                </a>
            </li>

            <li class="layui-nav-item user-selection">
                <a>
                    <img src="{% static 'Y-Admin/images/avatar.png' %}" class="layui-nav-img" alt="头像">
                    <cite>{{ nickname }}</cite>
                    <span class="layui-nav-more"></span>
                </a>
                <dl class="layui-nav-child">
                    <dd lay-unselect>
                        <a lay-event="userInfo">基本资料</a>
                    </dd>
                    <dd lay-unselect>
                        <a lay-event="editPwd">修改密码</a>
                    </dd>
                    <hr>
                    <dd lay-unselect>
                        <a href="{% url 'login:quit' %}">退出</a>
                    </dd>
                </dl>
            </li>
        </ul>
    </div>

    <!-- 左侧导航区域 -->
    <div class="layui-side ">
        <div class="layui-side-scroll">
            <ul class="layui-nav layui-nav-tree" lay-filter="lay-nav" lay-accordion="true">
                <li class="layui-nav-item">
                    <a lay-url="{% url 'diagnosis:main_layout' %}" lay-id="home">
                        <i class="ri-home-8-line"></i>&emsp;<cite>首页</cite>
                    </a>
                </li>

                <li class="layui-nav-item">
                    <a lay-id="#" lay-url="#">
                        <i class="ri-shield-keyhole-line"></i>&emsp;<cite>诊断</cite>
                    </a>
                    <dl class="layui-nav-child">
                        <dd>
                            <a lay-id="pic_upload" lay-url="{% url 'diagnosis:pic_upload' %}">
                                <cite>图片上传</cite>
                            </a>
                        </dd>
                        <dd>
                            <a lay-id="diagnosis-result" lay-url="{% url 'diagnosis:result_list' %}">
                                <cite>诊断结果</cite>
                            </a>
                        </dd>
                    </dl>
                </li>

                <li class="layui-nav-item">
                    <a lay-id="epidemic_map" lay-url="{% url 'epidemic_map:epidemic-map' %}">
                        <i class="ri-remixicon-line"></i>&emsp;<cite>疫情可视化</cite>
                    </a>
                </li>
                <li class="layui-nav-item">
                    <a lay-id="echarts" lay-url="{% url 'statistic:covid_19' %}">
                        <i class="ri-remixicon-line"></i>&emsp;<cite>疫情大数据</cite>
                    </a>
                </li>
                <li class="layui-nav-item">
                    <a lay-id="chat" lay-url="{% url 'chat:chat_index' %}">
                        <i class="ri-customer-service-2-line"></i>&emsp;<cite>医患沟通</cite>
                    </a>
                </li>
            </ul>

        </div>
    </div>


    <!--主体部分-->
    <div class="layui-body">
        <div class="layui-pagetabs">
            <div class="layui-icon admin-tabs-control layui-icon-refresh-3" lay-event="refresh"></div>
            <div class="layui-tab" lay-unauto lay-allowclose="true" lay-filter="lay-tab">
                <ul class="layui-tab-title">
                    <li lay-id="home" lay-url="{% url 'login:index' %}" class="layui-this">
                        <!-- <i class="ri-home-heart-line ri-xl"></i> -->
                        <i class="ri-home-8-line ri-xl"></i>
                    </li>
                </ul>
                <div class="layui-tab-content">
                    <div class="layui-tab-item layui-show">
                        <iframe src="{% url 'diagnosis:main_layout' %}" class="layui-iframe"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 移动端遮罩 -->
    <div class="site-mobile-shade"></div>
</div>

<script>
    //JavaScript代码区域
    function getCookie(cookiename) {
        let name = cookiename + "=";
        let cs = document.cookie.split(';');
        for (let i = 0; i < cs.length; i++) {
            let c = cs[i].trim();
            if (c.indexOf(name) == 0) return c.substring(name.length, c.length);
        }
    }

    var indexSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/chat/index/'
    );
    var username = getCookie('username');
    var online_user_list = new Array();


    indexSocket.onclose = function (e) {
        console.error("Index socket closed unexpectedly.");
    };

</script>

<!-- layui JS -->
<script src="{% static 'Y-Admin/layui/layui.js' %}"></script>
<!-- jQuery JS -->
<script src="{% static 'Y-Admin/js/jquery.js' %}"></script>
<!-- 公共JS -->
<script src="{% static 'Y-Admin/js/common.js' %}"></script>


</body>

</html>

code/COVID-AID/templates/index_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>患者首页</title>
</head>
<body>
你好，{{ nickname }}
<a href="{% url 'login:quit' %}">退出</a>
</body>
</html>