code/COVID-AID/chat/urls.py
"""为chat应用定义路由"""

from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('get_chat_room/<to_username>/', views.GetChatRoomView.as_view(), name='get_chat_room'),
    path('new_group_chat/', views.NewGroupChatView.as_view(), name='new_group_chat'),
    path('create_group_chat/', views.CreateGroupChatView.as_view(), name='create_group_chat'),
    path('get_group_chat/<room_name>/', views.GetGroupChatView.as_view(), name='get_group_chat'),
    path('chat_room/<room_name>/', views.room, name='chat_room'),
    path('index/', views.IndexView.as_view(), name='chat_index'),
]

code/COVID-AID/login/urls.py
from django.urls import path, re_path
from .views import quit, verify_account  # , page_error, page_not_found_error
from . import views

app_name = 'login'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),  # 登录系统
    path('quit/', quit, name='quit'),  # 退出系统
    path('verify_account/', verify_account, name='verify_account'),  # 异步验证账号密码
    re_path(r'usernames/(?P<username>[a-zA-Z0-9_\u4e00-\u9fa5\s·]+)/count/$', views.UsernameCountView.as_view()),
    re_path(
        r'phones/(?P<phone>[1](([3][0-9])|([4][5-9])|([5][0-3,5-9])|([6][5,6])|([7][0-8])|([8][0-9])|([9][1,8,9]))[0-9]{8})/count/$',
        views.PhoneCountView.as_view()),
    path('', views.IndexView.as_view(), name='index'),
]
# handler404 = page_not_found_error
# handler500 = page_error

code/COVID-AID/login/models.py
import uuid

# from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser


# from mptt.models import MPTTModel


# Create your models here.


class User(AbstractUser):
    """自定义用户模型类"""

    DOCTOR = 0
    PATIENT = 1
    IDENTITY_ITEMS = (
        (DOCTOR, '医生'),
        (PATIENT, '患者'),
    )

    nickname = models.CharField(verbose_name="昵称", max_length=50, null=False)
    phone = models.CharField(verbose_name="电话", max_length=50, unique=True, null=False)
    identity = models.PositiveIntegerField(choices=IDENTITY_ITEMS, verbose_name='身份')

    class Meta:
        db_table = 'user'
        verbose_name_plural = verbose_name = "用户"

    def __str__(self):
        return self.nickname


class Patient(models.Model):
    ct_image = models.CharField(verbose_name="CT图片", max_length=128)
    ct_gt_image = models.CharField(verbose_name='分割图片', max_length=128)

    RET_ITEMS = (
        ('YES', '阳性'),
        ('NO', '阴性'),
    )
    examine_ret = models.CharField(verbose_name='检测结果', max_length=30, choices=RET_ITEMS)

    patient_to_user = models.OneToOneField(User, related_name='patient', on_delete=models.CASCADE)

    class Meta:
        db_table = 'patient'
        verbose_name_plural = verbose_name = '患者'

code/COVID-AID/login/views.py
# import json
import re

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.hashers import make_password
from django.contrib.auth import logout, authenticate
from django.urls import reverse
from django.views import View
from django.http import HttpResponseForbidden, HttpResponse
from django.db import DatabaseError
# from .util import *
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator

from .models import User


# Create your views here.


# 登录
class LoginView(View):
    """用户登录"""

    def get(self, request):
        return render(request, 'login/login.html')

    @method_decorator(csrf_protect)
    def post(self, request):
        """登录逻辑"""
        # 接收参数
        # identity = request.POST.get('identity')

        username = request.POST.get('username')
        password = request.POST.get('password')

        # 校验参数
        if not all([username, password]):
            return HttpResponseForbidden("缺少必传参数")

        if not re.match(r'^[a-zA-Z0-9_\u4e00-\u9fa5\s·]+$', username):
            return HttpResponseForbidden("用户名不能有特殊字符")
        if not re.match(r'^[\S]{6,12}$', password):
            return HttpResponseForbidden("密码必须6到12位，且不能出现空格")

        # 从前端传来的identity参数是字符串，需转换
        # identity = int(identity)
        # 认证用户
        user = authenticate(username=username, password=password)
        if user is None:
            return render(request, 'login/login.html', {'login_errmsg': "账号或密码错误"})
        # else:
        #     if user.identity != identity:
        #         return render(request, 'login/login.html', {'login_errmsg': "身份不匹配"})

        # 状态保持
        login(request, user)

        next = request.GET.get('next')
        # 如果next存在则重定向至next
        if next:
            response = redirect(next)
        # 否则重定向至首页
        else:
            response = redirect(reverse('login:index'))

        # 设置cookie,将用户名保存至cookie当中
        response.set_cookie('username', username, max_age=3600 * 24 * 14)
        request.session['username'] = username
        request.session['nickname'] = user.nickname
        request.session['identity'] = user.identity

        # 响应结果:重定向至首页
        return response


# ajax验证
@csrf_protect
def verify_account(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    # identity = request.POST.get('identity')
    # identity = int(identity)
    print(username, password)
    # print(type(identity))
    response_data = {"info": 'false'}
    try:
        db_user = User.objects.get(username=username)
    except User.DoesNotExist as e:
        response_data = {"info": "username_false"}
        return JsonResponse(response_data, charset="utf-8")

    print(type(db_user.identity))
    if not db_user.check_password(password):
        print(db_user.password)
        response_data = {"info": "password_false"}
        return JsonResponse(response_data, charset="utf-8")
    # elif db_user.identity != identity:
    #     response_data = {'info': 'identity_false'}
    #     return JsonResponse(response_data, charset='utf-8')
    else:
        response_data = {"info": "true"}
        return JsonResponse(response_data, charset="utf-8")


# 退出方法
# @csrf_protect
def quit(request):
    # 清除状态保持信息
    logout(request)
    # 删除cookie中的username
    response = redirect(reverse('login:index'))
    response.delete_cookie('username')
    return response


# def page_not_found_error(request, exception):
#     return render(request, '404.html')
#
#
# def page_error(request):
#     return render(request, 'ztree.html')


# 首页模版
class IndexView(LoginRequiredMixin, View):
    """首页"""

    def get(self, request):
        # username = request.COOKIES.get('username')
        nickname = request.session.get('nickname')

        identity = request.session.get('identity')
        # identity需转化为整数类型
        identity = int(identity)
        # print(identity)

        if identity == User.DOCTOR:
            return render(request, 'index.html', {
                'nickname': nickname,
            })
        elif identity == User.PATIENT:
            # return render(request, 'index_patient.html', {
            #     'nickname': nickname,
            # })
            return render(request, 'index.html', {
                'nickname': nickname,
            })
        else:
            return HttpResponse("用户身份不合法")


class RegisterView(View):
    """注册视图"""

    def get(self, request):
        return render(request, 'login/register.html')

    @method_decorator(csrf_protect)
    def post(self, request):
        # 接收参数
        identity = request.POST.get('identity')

        username = request.POST.get('username')
        nickname = request.POST.get('nickname')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        phone = request.POST.get('phone')
        email = request.POST.get('email')

        print(identity, username, nickname, password2, password, phone, email)

        # 校验参数
        if not all([identity, username, nickname, password2, password, phone, email]):
            return HttpResponseForbidden('缺少必传参数')

        if not re.match(r'^[a-zA-Z0-9_\u4e00-\u9fa5\s·]+$', username):
            return HttpResponseForbidden("用户名不能有特殊字符")
        # if not re.match(r'',nickname):
        #     pass
        if not re.match(r'^[\S]{6,12}$', password):
            return HttpResponseForbidden("密码必须6到12位，且不能出现空格")
        if password2 != password:
            return HttpResponseForbidden("两次输入密码不一致")
        if not re.match(
                r'^[1](([3][0-9])|([4][5-9])|([5][0-3,5-9])|([6][5,6])|([7][0-8])|([8][0-9])|([9][1,8,9]))[0-9]{8}$',
                phone):
            return HttpResponseForbidden("请输入正确的手机号")
        if not re.match(r'^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$', email):
            return HttpResponseForbidden("请输入合法邮箱")

        # identity需转换
        identity = int(identity)

        # 保存用户数据
        try:
            user = User.objects.create_user(username=username, password=password, nickname=nickname, phone=phone,
                                            email=email, identity=identity)
        except DatabaseError:
            return render(request, 'login/register.html', {'register_errmsg': '注册失败'})

        # 实现状态保持（登录）
        login(request, user)

        response = redirect(reverse('login:index'))

        response.set_cookie('username', username, max_age=3600 * 24 * 14)
        request.session['nickname'] = nickname
        request.session['identity'] = identity
        request.session['username'] = username

        # 响应结果:重定向至首页
        return response


class UsernameCountView(View):
    """验证用户名是否重复注册"""

    @method_decorator(csrf_protect)
    def get(self, request, username):
        count = User.objects.filter(username=username).count()
        return JsonResponse({"count": count})


class PhoneCountView(View):
    """验证手机号是否重复"""

    @method_decorator(csrf_protect)
    def get(self, request, phone):
        count = User.objects.filter(phone=phone).count()
        return JsonResponse({"count": count})

code/COVID-AID/templates/login/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>后台管理-登陆</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Access-Control-Allow-Origin" content="*">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}" media="all">
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden
        }

        body {
            background: #1a1e21;
        }

        body:after {
            content: '';
            background-repeat: no-repeat;
            background-size: cover;
            -webkit-filter: blur(3px);
            -moz-filter: blur(3px);
            -o-filter: blur(3px);
            -ms-filter: blur(3px);
            filter: blur(3px);
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: -1;
        }

        .layui-container {
            width: 100%;
            height: 100%;
            overflow: hidden
        }

        .admin-login-background {
            width: 360px;
            height: 300px;
            position: absolute;
            left: 50%;
            top: 40%;
            margin-left: -180px;
            margin-top: -100px;
        }

        .logo-title {
            text-align: center;
            letter-spacing: 2px;
            padding: 14px 0;
        }

        .logo-title h1 {
            color: #0dcaf0;
            font-size: 25px;
            font-weight: bold;
        }

        .login-form {
            background-color: #fff;
            border: 1px solid #fff;
            border-radius: 3px;
            padding: 14px 20px;
            box-shadow: 0 0 8px #eeeeee;
        }

        .login-form .layui-form-item {
            position: relative;
        }

        .login-form .layui-form-item label {
            position: absolute;
            left: 1px;
            top: 1px;
            width: 38px;
            line-height: 36px;
            text-align: center;
            color: #d2d2d2;
        }

        .login-form .layui-form-item input {
            padding-left: 36px;
        }

        .captcha {
            width: 60%;
            display: inline-block;
        }

        .captcha-img {
            display: inline-block;
            width: 34%;
            float: right;
        }

        .captcha-img img {
            height: 34px;
            border: 1px solid #e6e6e6;
            height: 36px;
            width: 100%;
        }
    </style>
</head>
<body>
<div class="layui-container">
    <div class="admin-login-background">
        <div class="layui-form login-form">
            <form class="layui-form" action="{% url 'login:login' %}" method="post">
                {% csrf_token %} <!--随机码-->

                <div class="layui-form-item logo-title">
                    <h1>诊断辅助系统</h1>
                </div>
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-username" for="username"></label>
                    <input type="text" name="username" lay-verify="required|username" placeholder="用户名或者邮箱"
                           autocomplete="off" class="layui-input">
                </div>
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-password" for="password"></label>
                    <input type="password" name="password" lay-verify="required|password" placeholder="密码"
                           autocomplete="off" class="layui-input">
                </div>

                <!--图形验证码-->
                {#                <div class="layui-form-item">#}
                {#                    <label class="layui-icon layui-icon-vercode" for="captcha"></label>#}
                {#                    <input type="text" name="captcha" lay-verify="required|captcha" placeholder="图形验证码"#}
                {#                           autocomplete="off" class="layui-input verification captcha" value="xszg">#}
                {#                    <div class="captcha-img">#}
                {#                        <img id="captchaPic" src="../images/captcha.jpg">#}
                {#                    </div>#}
                {#                </div>#}

                <div class="layui-form-item">
                    <input type="checkbox" name="rememberMe" value="true" lay-skin="primary" title="记住密码">
                </div>
                <div class="layui-form-item" style="text-align: center">
                    <button class="layui-btn layui-btn-normal layui-inline" lay-submit=""
                            lay-filter="*">登 入
                    </button>
                    <button class="layui-btn layui-btn-normal layui-inline"
                            lay-filter="register"><a href="{% url 'login:register' %}">注 册</a>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'login/lib/jquery-3.4.1/jquery-3.4.1.min.js' %}" charset="utf-8"></script>
<script src="{% static 'layui/layui.js' %}" charset="utf-8"></script>
<script src="{% static 'login/lib/jq-module/jquery.particleground.min.js' %}" charset="utf-8"></script>
<script>
    layui.use(['layer', 'form', 'upload'], function (data) {
        var layer = layui.layer;
        var form = layui.form;
        var upload = layui.upload;
        var $ = layui.jquery;
        form.render();//表单渲染

        $(document).ready(function () {
            $('.layui-container').particleground({
                dotColor: '#7ec7fd',
                lineColor: '#7ec7fd'
            });
        });

        {% if login_errmsg %}
            layer.msg('{{ login_errmsg }}');
        {% endif %}

        //表单验证
        form.verify({
            username: function (value, item) { //value：表单的值、item：表单的DOM对象
                if (!new RegExp("^[a-zA-Z0-9_\u4e00-\u9fa5\\s·]+$").test(value)) {
                    return '用户名不能有特殊字符';
                }
                if (/(^\_)|(\__)|(\_+$)/.test(value)) {
                    return '用户名首尾不能出现下划线\'_\'';
                }
                if (/^\d+\d+\d$/.test(value)) {
                    return '用户名不能全为数字';
                }
            }, password: function (value, item) {
                var username = $('input[name="username"]').val();
                var password = $('input[name="password"]').val();
                var identity = $('select[name="identity"]').val();

                if (!/^[\S]{6,12}$/.test(value)) {
                    return '密码必须6到12位，且不能出现空格';
                }

                var infos = '';
                $.ajax({
                    type: 'post',
                    url: "{% url 'login:verify_account' %}",
                    async: false,
                    data: {
                        username: username,
                        password: password,
                        identity: identity,
                        csrfmiddlewaretoken: '{{ csrf_token  }}'
                    },
                    dataType: "json",
                    success: function (data) {
                        infos = data.info;
                    }
                });
                if (infos === 'username_false') {
                    return '用户不存在';
                }
                if (infos === 'password_false') {
                    return '密码错误';
                }
                if (infos === 'identity_false') {
                    return '身份不匹配'
                }
            }
        });
        //表单提交
        form.on('submit(*)', function (data) {
            var $ = layui.jquery;
            return true;
        });
    })

</script>
</body>
</html>

code/COVID-AID/templates/login/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>后台管理-登陆</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Access-Control-Allow-Origin" content="*">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}" media="all">
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden
        }

        body {
            background: #1a1e21;
        }

        body:after {
            content: '';
            background-repeat: no-repeat;
            background-size: cover;
            -webkit-filter: blur(3px);
            -moz-filter: blur(3px);
            -o-filter: blur(3px);
            -ms-filter: blur(3px);
            filter: blur(3px);
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: -1;
        }

        .layui-container {
            width: 100%;
            height: 100%;
            overflow: hidden
        }

        .admin-login-background {
            width: 360px;
            height: 300px;
            position: absolute;
            left: 50%;
            top: 40%;
            margin-left: -180px;
            margin-top: -100px;
        }

        .logo-title {
            text-align: center;
            letter-spacing: 2px;
            padding: 14px 0;
        }

        .logo-title h1 {
            color: #0dcaf0;
            font-size: 25px;
            font-weight: bold;
        }

        .login-form {
            position: relative;
            top: -35%;
            background-color: #fff;
            border: 1px solid #fff;
            border-radius: 3px;
            padding: 14px 20px;
            box-shadow: 0 0 8px #eeeeee;
        }

        .layui-form-item {
            position: relative;
        }

        .layui-form-item label {
            position: absolute;
            left: 1px;
            top: 1px;
            width: 38px;
            line-height: 36px;
            text-align: center;
            color: #d2d2d2;
        }

        .login-form .layui-form-item input {
            padding-left: 36px;
        }

        .captcha {
            width: 60%;
            display: inline-block;
        }

        .captcha-img {
            display: inline-block;
            width: 34%;
            float: right;
        }

        .captcha-img img {
            height: 34px;
            border: 1px solid #e6e6e6;
            height: 36px;
            width: 100%;
        }
    </style>
</head>
<body>
<div class="layui-container">
    <div class="admin-login-background">
        <div class="layui-form login-form">
            <form class="layui-form" action="{% url 'login:register' %}" method="post">
                {% csrf_token %} <!--随机码-->

                <div class="layui-form-item logo-title">
                    <h1>诊断辅助系统</h1>
                </div>

                <!--身份-->
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-friends" for="identity"></label>
                    <div class="layui-input-block">
                        <select name="identity" lay-verify="required">
                            <option value=""></option>
                            <option value="0">医生</option>
                            <option value="1">患者</option>
                        </select>
                    </div>
                </div>

                <!--用户名-->
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-username" for="username"></label>
                    <input type="text" name="username" lay-verify="required|username" placeholder="请输入用户名"
                           autocomplete="off" class="layui-input">
                </div>

                <!--昵称-->
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-user" for="nickname"></label>
                    <input type="text" name="nickname" lay-verify="required" placeholder="请输入昵称"
                           autocomplete="off" class="layui-input">
                </div>

                <!--密码-->
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-password" for="password"></label>
                    <input type="password" name="password" lay-verify="required|password" placeholder="请输入密码"
                           autocomplete="off" class="layui-input">
                </div>

                <!--确认密码-->
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-key" for="password2"></label>
                    <input type="password" name="password2" lay-verify="required|password|password2" placeholder="请再次输入密码"
                           autocomplete="off" class="layui-input">
                </div>

                <!--电话-->
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-cellphone" for="phone"></label>
                    <input type="text" name="phone" lay-verify="required|phone|phonecount" placeholder="请输入电话号码"
                           autocomplete="off" class="layui-input">
                </div>

                <!--邮箱-->
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-email" for="email"></label>
                    <input type="text" name="email" lay-verify="required|email" placeholder="请输入邮箱"
                           autocomplete="off" class="layui-input">
                </div>

                <!--图形验证码-->
                {#                <div class="layui-form-item">#}
                {#                    <label class="layui-icon layui-icon-vercode" for="captcha"></label>#}
                {#                    <input type="text" name="captcha" lay-verify="required|captcha" placeholder="图形验证码"#}
                {#                           autocomplete="off" class="layui-input verification captcha" value="xszg">#}
                {#                    <div class="captcha-img">#}
                {#                        <img id="captchaPic" src="../images/captcha.jpg">#}
                {#                    </div>#}
                {#                </div>#}

                <div class="layui-form-item" style="text-align: center">
                    <button class="layui-btn layui-btn-normal layui-inline" lay-submit=""
                            lay-filter="*">注 册
                    </button>
                    <button class="layui-btn layui-btn-normal layui-inline"
                            lay-filter="register"><a href="{% url 'login:login' %}">登 入</a>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'login/lib/jquery-3.4.1/jquery-3.4.1.min.js' %}" charset="utf-8"></script>
<script src="{% static 'layui/layui.js' %}" charset="utf-8"></script>
<script src="{% static 'login/lib/jq-module/jquery.particleground.min.js' %}" charset="utf-8"></script>
<script>
    layui.use(['layer', 'form', 'upload'], function (data) {
        var layer = layui.layer;
        var form = layui.form;
        var upload = layui.upload;
        var $ = layui.jquery;

        {% if register_errmsg %}
            layer.msg('{{ register_errmsg }}');
        {% endif %}

        form.render();//表单渲染

        $(document).ready(function () {
            $('.layui-container').particleground({
                dotColor: '#7ec7fd',
                lineColor: '#7ec7fd'
            });
        });
        //表单验证
        form.verify({
            /*用户名校验*/
            username: function (value, item) { //value：表单的值、item：表单的DOM对象
                if (!new RegExp("^[a-zA-Z0-9_\u4e00-\u9fa5\\s·]+$").test(value)) {
                    return '用户名不能有特殊字符';
                }
                if (/(^\_)|(\__)|(\_+$)/.test(value)) {
                    return '用户名首尾不能出现下划线\'_\'';
                }
                if (/^\d+\d+\d$/.test(value)) {
                    return '用户名不能全为数字';
                }

                /*判断用户名是否重复注册*/
                let flag = false
                $.ajax({
                    type: 'get',
                    url: "usernames/" + value + "/count/",
                    async: false,
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    dataType: 'json',
                    success: function (data) {
                        var count = data.count;

                        if (count > 0) {
                            flag = true
                        }
                    },
                    error: function (data) {
                        alert("无法连接后台");
                    }
                });
                if (flag) {
                    return "该用户已存在"
                }

            },
            /*密码校验*/
            password: function (value, item) {
                /*var username = $('input[name="username"]').val();
                var password = $('input[name="password"]').val();*/

                if (!/^[\S]{6,12}$/.test(value)) {
                    return '密码必须6到12位，且不能出现空格';
                }

                /*
                var infos = '';
                $.ajax({
                    type: 'post',




                {#url: '{{ path }}/verify_account',#}
                    async: false,
                    data: {
                        username: username,
                        password: password,




                {#csrfmiddlewaretoken: '{{ csrf_token  }}'#}
                    },
                    dataType: "json",
                    success: function (data) {
                        infos = data.info;
                    }
                });
                if (infos === 'false') {
                    return '账号密码错误';
                }
                */
            },
            /*确认密码校验*/
            password2: function (value, item) {
                var password1 = $('input[name=password]').val();
                var password2 = $('input[name=password2]').val();

                if (password2 != password1) {
                    return '两次输入密码不一致';
                }

            },
            {#手机号码重复验证#}
            phonecount: function (value, item) {
                let flag = false
                $.ajax({
                    type: 'get',
                    url: 'phones/' + value + '/count/',
                    async: false,
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    dataType: 'json',
                    success: function (data) {
                        count = data.count

                        if (count > 0) {
                            flag = true
                        }
                    },
                    error: function (data) {
                        alert('无法连接后台或电话格式不正确')
                    }
                })
                if (flag) {
                    return "改手机号码已注册"
                }
            }
        });
        //表单提交
        form.on('submit(*)', function (data) {
            var $ = layui.jquery;
            return true;
        });
    })

</script>
</body>
</html>