code/COVID-AID/chat/urls.py
"""为chat应用定义路由"""

from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('get_chat_room/<to_username>/', views.GetChatRoomView.as_view(), name='get_chat_room'),
    path('new_group_chat/', views.NewGroupChatView.as_view(), name='new_group_chat'),
    path('create_group_chat/', views.CreateGroupChatView.as_view(), name='create_group_chat'),
    path('get_group_chat/<room_name>/', views.GetGroupChatView.as_view(), name='get_group_chat'),
    path('chat_room/<room_name>/', views.room, name='chat_room'),
    path('index/', views.IndexView.as_view(), name='chat_index'),
]

code/COVID-AID/chat/models.py
import uuid

from django.db import models

from login.models import User


# Create your models here.


class ChatRoom(models.Model):
    """
    聊天室（供双人或多人）
    """
    name = models.CharField(max_length=255, null=True, verbose_name='聊天室名称')
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, null=False, editable=False)
    # name = models.CharField(max_length=128, verbose_name="群聊名称")
    members = models.ManyToManyField(User, verbose_name="聊天室成员")

    # 获取另一成员（仅针对双人聊天室）
    def get_another_member(self, member_name):
        members = self.members.all()
        if len(members) > 2:
            raise ValueError("members容量超出限制")

        another_member = members.exclude(username=member_name)[0]
        if not another_member:
            raise ValueError("members容量过小")
        return another_member

    # 获取聊天室内其他所有成员
    def get_other_members(self, member_name):
        members = self.members.all()

        other_members = members.exclude(username=member_name)
        if not other_members:
            raise ValueError("members容量过小")
        return other_members

    def __str__(self):
        return str(self.id)

    class Meta:
        db_table = 'chat_room'
        verbose_name_plural = verbose_name = '聊天室'


class Message(models.Model):
    """
    聊天信息模型
    """
    sender = models.ForeignKey(User, verbose_name="发送者", on_delete=models.CASCADE, related_name='sender_msg')
    chat_room = models.ForeignKey(ChatRoom, verbose_name="聊天室", on_delete=models.CASCADE, related_name='chatRoom_msg')
    text = models.CharField(max_length=255, verbose_name="信息内容")
    time = models.CharField(max_length=255, verbose_name="创建时间")
    READ = 'read'
    UNREAD = 'unread'
    STATUS_ITEM = (
        (READ, '已读'),
        (UNREAD, '未读'),
    )
    status = models.CharField(verbose_name="是否已读", choices=STATUS_ITEM, max_length=30, default=READ)
    receiver = models.ForeignKey(User, verbose_name="接收者", on_delete=models.CASCADE, related_name='receiver_msg')

    class Meta:
        db_table = "message"
        verbose_name_plural = verbose_name = "聊天信息"

    def __str__(self):
        return self.text

    @classmethod
    def get_receiver(cls, sender_name, chat_room):
        receiver = chat_room.get_another_member(sender_name)
        return receiver


class GroupMessage(models.Model):
    """
        群聊信息模型
    """
    sender = models.ForeignKey(User, verbose_name="发送者", on_delete=models.CASCADE, related_name="sender_g_msg")
    chat_room = models.ForeignKey(ChatRoom, verbose_name="聊天室", on_delete=models.CASCADE, related_name="chatRoom_g_msg")
    text = models.CharField(max_length=255, verbose_name="信息内容")
    time = models.CharField(max_length=255, verbose_name="创建时间")

    class Meta:
        db_table = "groupChat_message"
        verbose_name = verbose_name_plural = "群聊信息"

    def __str__(self):
        return self.text


class GroupMessageStatus(models.Model):
    """
        群聊信息状态模型
    """
    READ = 'read'
    UNREAD = 'unread'
    STATUS_ITEM = (
        (READ, '已读'),
        (UNREAD, '未读'),
    )
    status = models.CharField(verbose_name="是否已读", max_length=10, choices=STATUS_ITEM)
    message = models.ForeignKey(GroupMessage, on_delete=models.CASCADE, verbose_name="所属信息", related_name="gmsg_status")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="接收者", related_name="receiver_gmsgStatus")

    class Meta:
        db_table = 'group_msg_status'
        verbose_name = verbose_name_plural = "群聊信息状态"

    def __str__(self):
        return self.status

code/COVID-AID/chat/views.py
import json

from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.views import View
from django.http import HttpResponseForbidden, HttpResponse, JsonResponse

from login.models import User
from .models import ChatRoom, Message


# Create your views here.

def get_sidebar_infos(username, from_user):
    # 获取好友列表
    user_list = User.objects.all()
    # print(user_list)
    friend_list = []
    for user in user_list:
        if user.username == username:
            continue
        else:
            friend_item = {
                'username': user.username,
                'nickname': user.nickname,
                'identity': user.identity,
                # 'is_read': is_read,
            }
            friend_list.append(friend_item)

    # 得到聊天室列表（包括双人和多人）
    chat_list = ChatRoom.objects.filter(members=from_user)
    # 最近聊天列表
    to_user_list = []
    # 多人聊天室列表
    g_chat_list = []
    for chat in chat_list:
        members = chat.members.all()
        if len(members) == 2:
            to_user = chat.get_another_member(username)

            to_user_item = {
                'username': to_user.username,
                'nickname': to_user.nickname,
                'identity': to_user.identity,
                # 'is_read': is_read,
            }
            to_user_list.append(to_user_item)
        elif len(members) > 2:
            g_chat_item = {
                'g_chat_id': chat.id,
                'g_chat_name': chat.name,
            }

            g_chat_list.append(g_chat_item)

    return friend_list, to_user_list, g_chat_list


def room(request, room_name):
    """聊天室视图"""
    chat_room = ChatRoom.objects.get(id=room_name)
    username = request.session.get('username')
    from_user = User.objects.get(username=username)
    print(chat_room)

    # 获取侧边栏数据
    friend_list, to_user_list, g_chat_list = get_sidebar_infos(username, from_user)

    current_to_user = chat_room.get_another_member(username)

    return render(request, 'chat/single-chat.html', {
        'room_name_json': mark_safe(json.dumps(room_name)),
        'current_to_user': current_to_user,
        'friend_list': friend_list,
        'to_user_list': to_user_list,
        'g_chat_list': g_chat_list,
        # 'unread_sender_list': unread_sender_list,

    })


class IndexView(View):
    def get(self, request):
        # 获取数据
        username = request.session.get('username')
        if not username:
            print("登录状态有误，请重新登录")
            return HttpResponseForbidden("登录状态有误，请重新登录")

        # 处理数据
        from_user = User.objects.get(username=username)

        # 获取侧边栏数据
        friend_list, to_user_list, g_chat_list = get_sidebar_infos(username, from_user)

        # 封装数据
        context = {
            'friend_list': friend_list,
            'to_user_list': to_user_list,
            'self': from_user,
            'g_chat_list': g_chat_list,
            # 'unread_sender_list': unread_sender_list,
        }

        # 返回响应
        return render(request, 'chat/index.html', context)


class GetChatRoomView(View):
    """
        获取或创建双人聊天室
    """

    def get(self, request, to_username):
        print(to_username)
        # 接收数据
        from_username = request.session.get('username')
        from_user = User.objects.get(username=from_username)
        to_user = User.objects.get(username=to_username)
        print(to_user)

        # 处理数据
        # 获取聊天室列表
        chat_room_list = ChatRoom.objects.filter(members=from_user).filter(members=to_user).distinct()
        # 筛选得到双人聊天室列表
        single_room_list = []
        for chat_room_item in chat_room_list:
            if chat_room_item.members.count() == 2:
                single_room_list.append(chat_room_item)

        print(single_room_list)
        if not single_room_list:
            single_room = ChatRoom.objects.create()
            single_room.members.add(from_user, to_user)
        else:
            length = len(single_room_list)
            if length > 1:
                return HttpResponseForbidden("存在多个聊天室")
            single_room = single_room_list[0]

        print(single_room)
        print(single_room.members.all())
        room_name = single_room.id

        # 封装数据
        response = redirect(reverse('chat:chat_room', args=[room_name]))

        # 返回响应
        return response


class CreateGroupChatView(View):
    """
    新建群聊
    """

    def post(self, request):
        # 接收数据
        # print(request.POST)
        members = request.POST.get('members')
        members = json.loads(members)
        group_chat_name = request.POST.get('group_chat_name')
        # print(group_chat_name)

        # 创建群聊
        chat_room = ChatRoom.objects.create(name=group_chat_name)
        # 添加成员
        for username in members:
            user = User.objects.get(username=username)
            chat_room.members.add(user)
        self_name = request.session.get('username')
        self_user = User.objects.get(username=self_name)
        chat_room.members.add(self_user)

        print(chat_room)
        print(chat_room.members.all())

        # 下一步需要给多人聊天室创建单独的视图函数和前端页面

        return JsonResponse({
            'status': 'OK',
        })


class NewGroupChatView(View):
    """
    返回新建群聊表单页面
    """

    def get(self, request):
        return render(request, 'chat/view/createGroupChat.html')

    def post(self, request):
        # 从session中获取相应参数
        username = request.session.get('username')
        if not username:
            print("登录状态有误，请重新登录")
            return HttpResponseForbidden("登录状态有误，请重新登录")

        # print(username)
        # 处理参数
        user_list = User.objects.all()
        # print(user_list)
        friend_list = []
        index = 1
        for user in user_list:
            if user.username == username:
                continue
            else:
                friend_item = {
                    'value': index,
                    'title': user.nickname + '(' + user.username + ')',
                    'disabled': '',
                    'checked': '',
                }
                index = index + 1
                friend_list.append(friend_item)
        # print(friend_list)

        return JsonResponse({
            'status': 'OK',
            'friend_list': friend_list,
        })


class GetGroupChatView(View):
    """
        获取多人聊天室视图
    """

    def get(self, request, room_name):
        """

        :param request:
        :param room_name: 多人聊天室id
        :return:
        """
        print(room_name)

        # 获取聊天室对象
        chat_room = ChatRoom.objects.get(id=room_name)
        g_chat_name = chat_room.name
        members_count = chat_room.members.count()
        # 获取用户名
        username = request.session.get('username')
        if not username:
            return HttpResponseForbidden("您的登录状态有误，请重新登录")
        # 获取用户对象
        from_user = User.objects.get(username=username)

        # 获取侧边栏数据
        friend_list, to_user_list, g_chat_list = get_sidebar_infos(username, from_user)

        # 封装数据
        context = {
            'room_name_json': mark_safe(json.dumps(room_name)),
            # 'current_to_user': current_to_user,
            'friend_list': friend_list,
            'to_user_list': to_user_list,
            'g_chat_list': g_chat_list,
            'g_chat_name': g_chat_name,  # 聊天室名称
            'members_count': members_count,  # 成员数量
        }

        # 返回响应
        return render(request, 'chat/group-chat.html', context)

code/COVID-AID/templates/chat/view/createGroupChat.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- layui样式 -->
    <link rel="stylesheet" href="../../../static/layui/css/layui.css">
    <title>新建群聊</title>
    <style>
        #code {
            width: calc(100% - 200px);
            float: left;
            margin-right: 8px;
        }

        .layui-col-space15 {
            margin: 0px;
        }

        .foot {
            height: 49px !important;
            line-height: 49px;
            text-align: right;
            background-color: #f5f5f5;
            border-top: 1px #e5e5e5 solid;
        }

        .foot button {
            width: 62px;
            height: 28px;
            line-height: 28px;
            margin-left: 2px;
            margin-right: 15px;
        }

        .foot .close:hover {
            border-color: #1E9FFF;
        }
    </style>
</head>

<body style="background-color: #ffffff">
<form class="layui-form">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12" style="padding-bottom: 0;">
            <div class="layui-card">
                <div class="layui-card-body" pad15="">
                    <div class="layui-form" lay-filter="">

                        <!--群聊名称--->
                        <div class="layui-form-item">
                            <label class="layui-form-label">群聊名称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="group_chat_name" lay-verify="required" lay-vertype="tips"
                                       class="layui-input">
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="members"></div>
    <div class="foot">
        <button type="button" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit=""
                lay-filter="setmypass">确定
        </button>
        <button type="button" class="layui-btn layui-btn-primary layui-btn-sm close" lay-filter="close">取消</button>
    </div>
</form>
<!-- layui JS -->
<script src="../../../static/layui/layui.js"></script>
<script>

    layui.use(['form', 'jquery', 'layer', 'transfer'], function () {
        var form = layui.form;
        var $ = layui.jquery;
        var layer = layui.layer;
        var transfer = layui.transfer;

        //渲染
        var friend_list = new Array();
        $.ajax({
            url: "{% url 'chat:new_group_chat' %}",
            type: "post",
            dataType: 'json',
            data: {
                csrfmiddlewaretoken: '{{ csrf_token  }}'
            },
            success: function (data) {
                console.log(data.friend_list);
                friend_list = data.friend_list;

                transfer.render({
                    elem: '#members'  //绑定元素
                    , data: friend_list
                    , id: 'demo1' //定义索引
                    , title: ['好友列表', '邀请成员']
                });
            }
        });


        //提交
        form.on('submit(setmypass)', function (data) {
            let getData = transfer.getData('demo1');

            console.log(getData);

            //处理表单中的数据
            let members = new Array();
            for (let i = 0; i < getData.length; i++) {
                let nameString = getData[i].title;
                //console.log(nameString);
                let username = nameString.split('(')[1].slice(0, -1);
                //console.log(username);
                members.push(username);
            }
            console.log(members);

            let group_chat_name = $('input[name="group_chat_name"]').val();
            console.log(group_chat_name);

            //关闭当前弹出框
            var index = parent.layer.getFrameIndex(window.name);
            parent.layer.close(index);

            $.ajax({
                url: "{% url 'chat:create_group_chat' %}",
                type: 'post',
                dataType: 'json',
                data: {
                    members: JSON.stringify(members),
                    group_chat_name: group_chat_name,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    console.log(data.status);

                    //父页面刷新
                    parent.location.reload();
                }

            });

        });

        $('.close').click(function () {
            var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
            parent.layer.close(index); //再执行关闭
            return false;
        })


    });
</script>

</body>

</html>