code/COVID-AID/chat/urls.py
"""为chat应用定义路由"""

from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('get_chat_room/<to_username>/', views.GetChatRoomView.as_view(), name='get_chat_room'),
    path('new_group_chat/', views.NewGroupChatView.as_view(), name='new_group_chat'),
    path('create_group_chat/', views.CreateGroupChatView.as_view(), name='create_group_chat'),
    path('get_group_chat/<room_name>/', views.GetGroupChatView.as_view(), name='get_group_chat'),
    path('chat_room/<room_name>/', views.room, name='chat_room'),
    path('index/', views.IndexView.as_view(), name='chat_index'),
]

code/COVID-AID/diagnosis/urls.py
"""为diagnosis应用定义路由"""

from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'diagnosis'
urlpatterns = [
    path('pic_upload/', views.PicUploadView.as_view(), name='pic_upload'),
    path('pic_process/', views.PicProcessView.as_view(), name='pic_process'),
    path('result/', views.ResultView.as_view(), name='result'),
    path('main_layout/', views.MainLayoutView.as_view(), name='main_layout'),
    path('result_list/', views.ResultListView.as_view(), name='result_list'),
    path('result_detail/<num>/', views.ResultDetailView.as_view(), name='detail'),
    path('append_result/<img_url>/', views.PicProcessView.getPicture),
    path('update_result/<checked>/<result>/<idx>/', views.UpdateResultView.as_view())
]

code/COVID-AID/diagnosis/models.py
from django.db import models


# 用于储存检测结果 一次结果为一个元组
class DetectionResult(models.Model):
    # way:图片上传方式 为用户上传和医生上传
    # result:检测结果 为阴性与阳性
    # img_path:为上传图片的原图保存路径
    # processed_img_path:为分割处理后图片的保存路径
    # patient_id:患者的id号
    # index:结果序号
    # checked:是否被复查
    index = models.AutoField(primary_key=True)
    way = models.CharField(max_length=20)
    result = models.CharField(max_length=10)
    processed_img_path = models.CharField(max_length=100)
    img_path = models.CharField(max_length=100)
    patient_id = models.CharField(max_length=20)
    checked = models.BooleanField(default=False)

code/COVID-AID/diagnosis/views.py
import os
import time

from django.urls import reverse

from diagnosis.recognize import recognize
from diagnosis.segmentation import inference
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from diagnosis.models import DetectionResult

# Create your views here.

# 返回在模板中的参数
context = {}


class Util:
    index = 173


class PicProcessView(View):

    def getPicture(img_url):
        url = "models/segment/Results/Lung infection segmentation/Inf-Net/Append_result/%s" % img_url
        image_data = open(url, "rb").read()
        return HttpResponse(image_data, content_type="image/png")

    # 上传图片 分割后处理
    @csrf_exempt
    def post(self, request):
        file_url = ""
        user_id = request.POST.get("userId")
        file = request.FILES.get('file')  # 获取文件对象，包括文件名文件大小和文件内容
        curttime = time.strftime("%Y-%m-%d")
        # 规定上传目录
        upload_url = os.path.join(settings.MEDIA_ROOT, 'attachment', curttime)
        # 判断文件夹是否存在
        folder = os.path.exists(upload_url)
        detectionResult = ""
        if not folder:
            os.makedirs(upload_url)
            print("创建文件夹")
        if file:
            file_name = file.name
            # 表示上传文件的后缀
            etx = ""
            # 判断文件是是否重名，重名了，文件名加时间
            if os.path.exists(os.path.join(upload_url, file_name)):
                name, etx = os.path.splitext(file_name)
                addtime = time.strftime("%Y%m%d%H%M%S")
                finally_name = name + "_" + addtime + etx
            else:
                finally_name = file.name
                name, etx = os.path.splitext(file_name)

            # 文件分块上传
            upload_file_to = open(os.path.join(upload_url, finally_name), 'wb+')
            for chunk in file.chunks():
                upload_file_to.write(chunk)
            upload_file_to.close()

            # 文件原图的URl
            file_upload_url = settings.MEDIA_URL + 'attachment/' + curttime + '/' + finally_name
            # 用于存储在数据库中的原图的url
            save_url = '/attachment/' + curttime + '/' + finally_name
            # 处理后图片的URL
            file_processed_url = os.path.join(upload_url, "res_" + finally_name + ".png")
            # 对类别进行识别
            context['judge'],con = recognize(os.path.join(upload_url, finally_name))
            # 对图片进行分割并返回分割图片的路径
            context['append_img'] = inference(os.path.join(upload_url, finally_name), file_processed_url)

            identity = request.session.get('identity')
            way = ""
            if identity == 0:
                way = "医生上传"
            elif identity == 1:
                way = "患者上传"

            detectionResult = DetectionResult(way=way, result=context['judge'],
                                              processed_img_path=context['append_img'],
                                              img_path=save_url, patient_id=user_id)
            detectionResult.save()
            Util.index = detectionResult.index
        else:
            print("no file")

        print(context)
        print("finished")
        return redirect("/diagnosis/result_detail/" + str(Util.index) + "/")


class PicUploadView(LoginRequiredMixin, View):
    """图片上传"""

    @method_decorator(xframe_options_sameorigin)
    def get(self, request):
        return render(request, 'diagnosis/pic_upload.html')


class MainLayoutView(View):
    @method_decorator(xframe_options_sameorigin)
    def get(self, request):
        return render(request, 'diagnosis/main_layout.html')


class ResultListView(View):
    @method_decorator(xframe_options_sameorigin)
    def get(self, request):
        temp = DetectionResult.objects.all()
        print(temp)
        context['temp'] = temp
        unchecked = DetectionResult.objects.filter(checked=0)
        context['unchecked'] = unchecked
        checked = DetectionResult.objects.filter(checked=1)
        context['checked'] = checked
        return render(request, 'diagnosis/ct_resultList.html', context)


class ResultDetailView(View):
    @method_decorator(xframe_options_sameorigin)
    def get(self, request, num):
        # 从数据库中调取对应编号的患者检测数据 用于展示界面
        print("提取index为" + str(num) + "的患者数据")
        temp = DetectionResult.objects.get(index=num)
        print("----------------------------------------------")
        print(temp.img_path)
        print(temp.processed_img_path)
        print("----------------------------------------------")
        context['temp'] = temp
        return render(request, 'diagnosis/result_detail.html', context)


class ResultView(LoginRequiredMixin, View):
    """诊断结果显示"""
    pass


class UpdateResultView(View):
    @method_decorator(xframe_options_sameorigin)
    def get(self, request, checked, result, idx):
        print(idx)
        temp = DetectionResult.objects.get(index=idx)
        temp.result = result
        temp.checked = checked
        temp.save()
        return redirect("/diagnosis/result_list/")

code/COVID-AID/templates/diagnosis/ct_resultList.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>CT检测结果</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">

    <!--图标库-->
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css'>

    <!--核心样式-->
    <link rel="stylesheet" href="{% static 'other/css/result/style.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
</head>
<body>

<div class='app'>
    <main class='project'>
        <div class='project-info'>
            <h1>CT检测结果</h1>
        </div>
        <div class='project-tasks'>
            <div class='project-column'>
                <div class='project-column-heading'>
                    <h2 class='project-column-heading__title'>已复查结果</h2>
                    <button class='project-column-heading__options'><i class="fas fa-ellipsis-h"></i></button>
                </div>
                {% for item in checked %}
                    <div class='task' draggable='true'>
                        {% if item.result == "阴性" %}
                        <div class='task__tags'><span class='task__tag task__tag--design'>{{ item.result }}</span>
                            <button class='task__options'><i class="fas fa-ellipsis-h"></i></button>
                        </div>
                        {% else %}
                        <div class='task__tags'><span class='task__tag task__tag--copyright'>{{ item.result }}</span>
                            <button class='task__options'><i class="fas fa-ellipsis-h"></i></button>
                        </div>
                        {% endif %}
                        <p>患者编号：{{ item.patient_id }}</p>
                        <div class='task__stats'>
                            <span><time datetime="2021-11-24T20:00:00"><i class="fas fa-flag"></i>
                                {% if item.checked == 1 %}
                                    已复查
                                {% else %}
                                    未复查
                                {% endif %}
                            </time></span>
                            &nbsp&nbsp&nbsp&nbsp&nbsp<a href="/diagnosis/result_detail/{{ item.index }}/">
                            <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">详细信息</button>
                        </a>
                            &nbsp&nbsp
                            <button onclick="copyUrl(this);" class="layui-btn layui-btn-primary layui-btn-xs">复制链接
                            </button>
                            <textarea style="opacity: 0;">/diagnosis/result_detail/{{ item.index }}/</textarea>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class='project-column'>
                <div class='project-column-heading'>
                    <h2 class='project-column-heading__title'>历史检测记录</h2>
                    <button class='project-column-heading__options'><i class="fas fa-ellipsis-h"></i></button>
                </div>
                {% for item in temp %}
                    <div class='task' draggable='true'>
                        {% if item.result == "阴性" %}
                        <div class='task__tags'><span class='task__tag task__tag--design'>{{ item.result }}</span>
                            <button class='task__options'><i class="fas fa-ellipsis-h"></i></button>
                        </div>
                        {% else %}
                        <div class='task__tags'><span class='task__tag task__tag--copyright'>{{ item.result }}</span>
                            <button class='task__options'><i class="fas fa-ellipsis-h"></i></button>
                        </div>
                        {% endif %}
                        <p>患者编号：{{ item.patient_id }}</p>
                        <div class='task__stats'>
                            <span><time datetime="2021-11-24T20:00:00"><i class="fas fa-flag"></i>
                                {% if item.checked == 1 %}
                                    已复查
                                {% else %}
                                    未复查
                                {% endif %}
                            </time></span>
                            &nbsp&nbsp&nbsp&nbsp&nbsp<a href="/diagnosis/result_detail/{{ item.index }}/">
                            <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">详细信息</button>
                        </a>
                            &nbsp&nbsp
                            <button onclick="copyUrl(this);" class="layui-btn layui-btn-primary layui-btn-xs">复制链接
                            </button>
                            <textarea style="opacity: 0;">/diagnosis/result_detail/{{ item.index }}/</textarea>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class='project-column'>
                <div class='project-column-heading'>
                    <h2 class='project-column-heading__title'>待复查</h2>
                    <button class='project-column-heading__options'><i class="fas fa-ellipsis-h"></i></button>
                </div>
                {% for item in unchecked %}
                    <div class='task' draggable='true'>
                        {% if item.result == "阴性" %}
                        <div class='task__tags'><span class='task__tag task__tag--design'>{{ item.result }}</span>
                            <button class='task__options'><i class="fas fa-ellipsis-h"></i></button>
                        </div>
                        {% else %}
                        <div class='task__tags'><span class='task__tag task__tag--copyright'>{{ item.result }}</span>
                            <button class='task__options'><i class="fas fa-ellipsis-h"></i></button>
                        </div>
                        {% endif %}
                        <p>患者编号：{{ item.patient_id }}</p>
                        <div class='task__stats'>
                            <span><time datetime="2021-11-24T20:00:00"><i class="fas fa-flag"></i>
                                {% if item.checked == 1 %}
                                    已复查
                                {% else %}
                                    未复查
                                {% endif %}
                            </time></span>
                            &nbsp&nbsp&nbsp&nbsp&nbsp<a href="/diagnosis/result_detail/{{ item.index }}/">
                            <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">详细信息</button>
                        </a>
                            &nbsp&nbsp
                            <button onclick="copyUrl(this);" class="layui-btn layui-btn-primary layui-btn-xs">复制链接
                            </button>
                            <textarea style="opacity: 0;">/diagnosis/result_detail/{{ item.index }}/</textarea>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
</div>
<!--图标库-->
<script src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js'></script>

<script src="{% static 'other/js/result/script.js' %}"></script>

<script src="{% static 'layui/layui.js' %}"></script>
<script>
    function copyUrl(e) {
        //console.log(e);
        let fatherNode = e.parentNode;
        let nodeList = fatherNode.childNodes;
        //console.log(nodeList);
        let urlText = nodeList[7];
        console.log(urlText);
        urlText.select();
        document.execCommand("copy");

        layui.use('layer', function () {
            let layer = layui.layer;

            layer.msg('复制成功');
        });
    }
</script>
</body>
</html>

code/COVID-AID/templates/diagnosis/main_layout.html
{% load static %}

<!--本页面为首页的初始界面-->
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="{% static 'other/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'other/css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-content text-center p-md">

                            <h2><span class="text-navy">Covid-aid 线上辅助诊断系统</span>
                            为您提供贴心的CT图像辅助诊断服务 <br/>祝您健康</h2>

                            <a>可点击此处查看使用说明</a>


                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="ibox float-e-margins">
                        <div class="ibox-content text-center p-md">

                            <h3 class="m-b-xxs">深度学习处理CT图像</h3>
                            <p>Avalible configure options</p>
                            <span class="simple_tag">患病概率预测</span>
                            <span class="simple_tag">病灶区域的标识</span>
                            <span class="simple_tag">患者分类</span>
                            <span class="simple_tag">辅助诊断</span>
                            <div class="m-t-md">
                                <div class="p-lg ">
<!--                                <a href="dashboard_4.html"><img class="img-responsive img-shadow" src="{% static 'img/main/lung.jpg' %}" vertical-align="middle" alt=""></a>-->
                                    <a href="{% url 'diagnosis:pic_upload' %}">点击使用</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-lg-6">
                    <div class="ibox float-e-margins">
                        <div class="ibox-content text-center p-md">

                            <h3 class="m-b-xxs">流行范围可视化</h3>
                            <p>Avalible configure options</p>
                            <span class="simple_tag">更新新病例轨迹</span>
                            <span class="simple_tag">结合原有大数据</span>
                            <span class="simple_tag">辅助疫情防控</span>
                            <div class="m-t-md">
                                <div class="p-lg">
<!--                                <a href="dashboard_4_1.html"><img class="img-responsive img-shadow" src="{% static 'img/main/lung.jpg' %}" vertical-align="middle" alt=""></a>-->
                                    <a href="{% url 'diagnosis:result_list' %}">点击使用</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </body>
</html>

code/COVID-AID/templates/diagnosis/pic_upload.html
<!DOCTYPE html>
{% load static %}
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{% static 'other/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'other/css/dropzone/basic.css' %}" rel="stylesheet">
    <link href="{% static 'other/css/dropzone/dropzone.css' %}" rel="stylesheet">
    <link href="{% static 'other/css/style.css' %}" rel="stylesheet">
</head>

<body>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>CT在线检测工具</h2>
                    <ol class="breadcrumb">
                        <li class="active">
                            <strong>CT Recognition Tool Online</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
        <div class="wrapper wrapper-content animated fadeIn">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
<!--                        <h5>图片/文件上传区域</h5>-->
<!--                        <div class="layui-form-item">-->
                        <label class="layui-form-label">图片/文件上传区域</label>
                            <div class="layui-input-inline">
                                <label for="user_id">患者编号</label><input id="user_id" type="text" placeholder="请输入患者编号" onchange="changeUserId()">
                            </div>
<!--                        </div>-->
                    </div>
                    <div class="ibox-content">
                        <!--图片上传表单-->
                        <form id="my-awesome-dropzone" class="dropzone" method="post" action="{% url 'diagnosis:pic_process' %}" >
                            {% csrf_token %}
                            <input id="user_input" type="text" name="userId" style="display: none"/>
                            <div class="dropzone-previews">点击或拖拽上传</div>
                            <button id = "submit" class="btn btn-primary pull-right">提交检测</button>
                        </form>

                    </div>
                </div>
            </div>
            </div>

            </div>




    <!-- Mainly scripts -->
    <script src="{% static 'other/js/jquery-2.2.3.min.js' %}"></script>
    <script>
        function changeUserId(){
            document.getElementById("user_input").value = document.getElementById("user_id").value
        }
    </script>

    <!-- DROPZONE -->
    <script src="{% static 'other/js/dropzone/dropzone.js' %}"></script>
    <script>
    $("#my-awesome-dropzone").submit(function(){
<!--        return false;-->
    })
    Dropzone.options.myAwesomeDropzone = {

        autoProcessQueue: false,
        acceptedFiles: ".png,.jpg,.gif,.bmp,.jpeg,.gz",
        maxFilesize: 1,
        parallelUploads: 10,
        addRemoveLinks: true,
        init: function() {
        var submitButton = document.querySelector("#submit")
        myDropzone = this; // closure

        submitButton.addEventListener("click", function() {
            myDropzone.processQueue();
            // autoProcessQueue: true// Tell Dropzone to process all queued files.
        });

        // You might want to show the submit button only when
        // files are dropped here:
        this.on("addedfile", function() {
          // Show submit button here and/or inform user to click it.
        });

        }
    };
    </script>
</body>

</html>

code/COVID-AID/templates/diagnosis/result_detail.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <link href="{% static 'layui/css/layui.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'other/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'other/css/result/detail.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'layui/css/modules/layer/default/layer.css' %}" rel="stylesheet" type="text/css" />
    <title>Vienna</title>
</head>

<body>

    <!-- PRELOADER -->
    <div class="wpc-preloader">
        <div class="wrap-load">
            <div class="cssload-tetrominos">
                <div class="cssload-tetromino cssload-box1"></div>
                <div class="cssload-tetromino cssload-box2"></div>
                <div class="cssload-tetromino cssload-box3"></div>
                <div class="cssload-tetromino cssload-box4"></div>
            </div>
        </div>
    </div>

    <!-- HEADER -->
    <header>
        <div class="container-fluid padd-l-100 marg-lg-b15 wpc-header">
            <div class="row">
            </div>
        </div>
    </header>

     <!-- CONTENT -->

   <div class="container-fluid padd-l-100 marg-lg-t30 no-padd-xs">
       <div class="row" margin-left = "-69px">
           <div class="col-xs-12 col-md-8 no-padding">
                <div class="gallery-section wpc-h full-page">
                    <div class="s-back-switch slide-wrap wpc-h">
                        <img id = "pic" style="display:block" src="{{ MEDIA_URL }}{{ temp.img_path }}" alt="gallery" width="666px" height="auto">
<!--                        <img id = "pic_res" style="display:block" src="{{ MEDIA_URL }}{{ temp.processed_img_path }}" alt="gallery" class="s-img-switch">-->
                        <img id = "pic_res" style="display:none" src="{{ MEDIA_URL }}{{ temp.processed_img_path }}" alt="gallery" width="666px" height="auto">
                    </div>
                </div>
           </div>
           <div class="col-md-4">
               <aside class="wpc-sidebar classic no-opacity">
                <i class="fa fa-times"></i>
                  <div class="heading marg-lg-b50">{{ temp.result }}</div>
                  <div class="info">
                      该检测结果仅为模型处理后所得结果 <br class="visible-lg-large">
                      <div class="marg-lg-t20 info-group">
                          <p><span class="detail-info">患者编号:{{temp.patient_id}}</span></p>
                          <p><span class="detail-info">检测类型:{{temp.way}}</span></p>
                          <p><span class="detail-info">检测时间:2020/1/22</span></p>
                      </div>
                  </div>
                  <div class="btn-toggle-slider small modern">
                      <a href="" class="slide-prev slide"><i class="fa fa-angle-left"></i></a>
                      <a href="" class="slide-next slide"><i class="fa fa-angle-right"></i></a>
                  </div>
                   <br><br><br>
                    <button id = "convert_button" type="button" class="layui-btn layui-btn-radius">分割图像</button>
                    <button id = "check_button" type="button" class="layui-btn layui-btn-radius">复查</button>
               </aside>
           </div>
       </div>
   </div>



    <!-- FOOTER -->

    <footer class="wpc-footer">
        <div class="container-fluid padd-l-100">
            <div class="row">
            </div>
        </div>
    </footer>


    <script src="{% static 'other/js/jquery-2.2.3.min.js' %}"></script>
    <script src="{% static 'other/js/main.js' %}"></script>
    <script src="{% static 'layui/lay/modules/layer.js' %}"></script>
    <script>
        $("#convert_button").click(function(){
                   $("#pic").toggle();
                   $("#pic_res").toggle();
            }
        );
        $("#check_button").click(function(){
            layer.confirm('请输入你的复查结果', {
                  btn: ['阳性','阴性'] //按钮
                }, function(){
                  location.href = "/diagnosis/update_result/1/阳性/{{temp.index}}/"
                },function(){
                  location.href = "/diagnosis/update_result/1/阴性/{{temp.index}}/"
                });
        })
    </script>

</body>

</html>